'use client';

import { useState } from 'react';
import { useMutation } from '@apollo/client';
import { REQUEST_REPLAN, RESPOND_TO_PLAN_RUN, TODAY_PLAN_QUERY, UPDATE_TASK } from '../lib/queries';
import { fromDatetimeLocalValue, toDatetimeLocalValue } from '../lib/datetime-local';
// Sleek/futuristic visual redesign (2026-09-01): Nova appears here, in the
// plan card's steady state, as the small "assistant is present" cue next to
// the status copy — see NovaAvatar.tsx for why it's a hand-rolled CSS glow
// rather than an image asset.
import { NovaAvatar } from './NovaAvatar';

interface PlanChange {
  id: string;
  changeType: string;
  previousStart?: string | null;
  proposedStart: string;
  proposedEnd: string;
  reason: string;
  task: { id: string; title: string; priority: number; estimatedDurationMinutes?: number | null };
}

interface PlanRun {
  id: string;
  status: 'PROPOSED' | 'ACCEPTED' | 'EDITED' | 'REJECTED';
  modelUsed: string;
  generatedAt: string;
  // Auto-plan indicator increment: every real trigger PlannerService knows
  // about writes a string here — 'manual_request' for the "Generate my
  // plan" button, or one of eight `auto_*` values for a real automatic
  // trigger (see isAutoGenerated below). Was always a real column and a
  // real GraphQL field before this increment; this component just never
  // asked for it.
  triggerEvent: string;
  // Morning plan auto-apply increment (2026-09-05) — non-null and in the
  // future means this plan is still PROPOSED and will auto-apply itself at
  // this moment unless reviewed/changed first (see
  // MorningPlanService/SchedulerService.autoApplyDuePlanRuns). Only ever
  // set on a morning-triggered plan when the person's own
  // autoApplyMorningPlanEnabled preference is on; every other plan
  // (manual, or any other auto-replan trigger) always has this null.
  autoApplyAt?: string | null;
  diff: { summary: string; changes: PlanChange[] };
}

// Morning plan auto-apply increment (2026-09-05): a real countdown, not
// just "this will auto-apply eventually" — showing exactly when means the
// person always knows how much time they actually have to look at a
// morning-generated plan before it takes effect on its own, rather than
// discovering after the fact that it already had.
function formatAutoApplyNotice(autoApplyAt: string): string {
  const target = new Date(autoApplyAt).getTime();
  const minutesLeft = Math.round((target - Date.now()) / 60000);
  const clockTime = new Date(autoApplyAt).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  if (minutesLeft <= 0) return 'Applying automatically any moment now, unless you make a change first.';
  if (minutesLeft < 60) return `Auto-applies in ${minutesLeft} min (at ${clockTime}) unless you make a change first.`;
  const hours = Math.floor(minutesLeft / 60);
  const mins = minutesLeft % 60;
  const hoursLabel = mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  return `Auto-applies in ${hoursLabel} (at ${clockTime}) unless you make a change first.`;
}

// Every automatic trigger source in PlannerService (task.completed,
// calendar.changed, habit.completed, checkin.logged, routine.completed,
// journal.entryCreated, focusSession.completed, reflection.submitted) emits
// its triggerEvent as `auto_<something>` — a plain, consistent prefix
// rather than an enum, so telling "was this auto-generated" apart from
// "did I tap the button" never needs to know the full list of trigger
// names, just this one prefix check.
function isAutoGenerated(triggerEvent: string | undefined | null): boolean {
  return !!triggerEvent?.startsWith('auto_');
}

// Free-form plan editing increment: an open task the AI could have proposed
// but didn't — same shape TODAY_PLAN_QUERY's `tasks` field already returns,
// passed down from the Today page rather than fetched again here.
interface OpenTask {
  id: string;
  title: string;
}

// One pending local edit per change, keyed by PlanChange.id — kept as the
// raw "YYYY-MM-DDTHH:mm" string straight from the datetime-local input
// rather than converting to ISO immediately, so re-opening that row's
// editor shows back exactly what was typed; conversion to a real ISO
// datetime only happens once, when actually building the mutation's
// `edits` array in handleSaveEdits.
interface PendingEdit {
  proposedStartLocal?: string;
  remove?: boolean;
}

// Free-form plan editing increment: one pending "add this task" entry,
// keyed by taskId (there's no PlanChange.id yet — it doesn't exist until
// the server actually creates one). Kept local-only until Save & apply
// changes, same "nothing real happens until an explicit action" principle
// PendingEdit already follows.
interface PendingAdd {
  taskId: string;
  title: string;
  proposedStartLocal: string;
}

// Editing a task's own details increment: the inline "Edit task" form's
// local draft state, keyed by PlanChange.id (not taskId — this is about
// this row's editor, not the task record itself).
interface TaskDraft {
  title: string;
  priority: number;
  estimatedDurationMinutes: number;
}

function formatTime(iso: string) {
  return new Date(iso).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
}

// "Generate my plan" (AI daily planning increment, API Design Document
// §4.4). A PROPOSED plan run is shown as a review card the user must
// explicitly Accept, Reject, or now Edit — nothing is written to real
// tasks until they do (PRD §7.3's "propose, don't auto-commit" principle).
// Editing a proposed AI plan increment: each suggested change can be moved
// to a new time or dropped before saving, all still client-side/local until
// "Save & apply changes" is tapped — the same "nothing real happens until
// an explicit action" principle Accept/Reject already followed, just
// extended to cover the in-between editing itself.
export function AiPlanCard({
  latestPlanRun,
  openTasks = [],
}: {
  latestPlanRun?: PlanRun | null;
  openTasks?: OpenTask[];
}) {
  const [error, setError] = useState<string | null>(null);
  const [pendingEdits, setPendingEdits] = useState<Record<string, PendingEdit>>({});
  const [editingChangeId, setEditingChangeId] = useState<string | null>(null);
  // Free-form plan editing increment.
  const [pendingAdds, setPendingAdds] = useState<Record<string, PendingAdd>>({});
  const [isAdding, setIsAdding] = useState(false);
  const [addTaskId, setAddTaskId] = useState('');
  const [addTimeLocal, setAddTimeLocal] = useState('');
  // Editing a task's own details increment.
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null);
  const [taskDraft, setTaskDraft] = useState<TaskDraft | null>(null);
  const [taskSaveError, setTaskSaveError] = useState<string | null>(null);
  const refetchQueries = [{ query: TODAY_PLAN_QUERY }];

  const [requestReplan, { loading: generating }] = useMutation(REQUEST_REPLAN, { refetchQueries });
  const [respond, { loading: responding }] = useMutation(RESPOND_TO_PLAN_RUN, { refetchQueries });
  const [updateTask, { loading: savingTaskDetails }] = useMutation(UPDATE_TASK, { refetchQueries });

  function resetLocalEditState() {
    setPendingEdits({});
    setEditingChangeId(null);
    setPendingAdds({});
    setIsAdding(false);
    setAddTaskId('');
    setAddTimeLocal('');
    setEditingTaskId(null);
    setTaskDraft(null);
    setTaskSaveError(null);
  }

  function startEditingTask(change: PlanChange) {
    setEditingChangeId(null); // mutually exclusive with the time editor
    setEditingTaskId(change.id);
    setTaskSaveError(null);
    setTaskDraft({
      title: change.task.title,
      priority: change.task.priority,
      estimatedDurationMinutes: change.task.estimatedDurationMinutes ?? 30,
    });
  }

  async function handleSaveTaskDetails(change: PlanChange) {
    if (!taskDraft) return;
    setTaskSaveError(null);
    const result = await updateTask({
      variables: {
        id: change.task.id,
        input: {
          title: taskDraft.title,
          priority: taskDraft.priority,
          estimatedDurationMinutes: taskDraft.estimatedDurationMinutes,
        },
      },
    });
    const payload = result.data?.updateTask;
    if (payload?.errors?.length) {
      setTaskSaveError(payload.errors[0].message);
      return;
    }
    // Marks this row as "touched" so the footer switches to Save & apply
    // changes — needed because a task-detail edit (title/priority/duration)
    // is a real write to the task itself, applied immediately, but its
    // *plan* effect (an edited duration can change proposedEnd and needs
    // re-validating — see PlannerService.respondToPlanRun's EDIT branch)
    // only takes effect once the plan response is actually saved. An empty
    // entry is enough: handleSaveEdits already sends `remove: false,
    // proposedStart: undefined` for any changeId with neither set, which
    // the backend treats as "no time edit requested," triggering exactly
    // the duration recompute this needs.
    setPendingEdits((prev) => ({ ...prev, [change.id]: { ...prev[change.id] } }));
    setEditingTaskId(null);
    setTaskDraft(null);
  }

  async function handleGenerate() {
    setError(null);
    resetLocalEditState();
    const result = await requestReplan();
    const payload = result.data?.requestReplan;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    }
  }

  async function handleRespond(decision: 'ACCEPT' | 'REJECT') {
    if (!latestPlanRun) return;
    setError(null);
    const result = await respond({ variables: { id: latestPlanRun.id, decision } });
    const payload = result.data?.respondToPlanRun;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    } else {
      resetLocalEditState();
    }
  }

  async function handleSaveEdits() {
    if (!latestPlanRun) return;
    setError(null);
    const edits = Object.entries(pendingEdits).map(([changeId, edit]) => ({
      changeId,
      remove: edit.remove ?? false,
      proposedStart: edit.remove || !edit.proposedStartLocal ? undefined : fromDatetimeLocalValue(edit.proposedStartLocal),
    }));
    // Free-form plan editing increment.
    const adds = Object.values(pendingAdds).map((add) => ({
      taskId: add.taskId,
      proposedStart: fromDatetimeLocalValue(add.proposedStartLocal),
    }));
    const result = await respond({ variables: { id: latestPlanRun.id, decision: 'EDIT', edits, adds } });
    const payload = result.data?.respondToPlanRun;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    } else {
      resetLocalEditState();
    }
  }

  // Free-form plan editing increment: a task already carrying a change on
  // this plan (AI-proposed, whether or not it's currently marked for
  // removal) or already staged in pendingAdds can't be picked again — same
  // "one change per task per plan" invariant the backend itself enforces.
  const plannedTaskIds = new Set([
    ...(latestPlanRun?.diff.changes.map((c) => c.task?.id).filter(Boolean) as string[]) ?? [],
    ...Object.keys(pendingAdds),
  ]);
  const availableTasksToAdd = openTasks.filter((t) => !plannedTaskIds.has(t.id));

  function handleAddTask() {
    if (!addTaskId || !addTimeLocal) return;
    const task = openTasks.find((t) => t.id === addTaskId);
    if (!task) return;
    setPendingAdds((prev) => ({ ...prev, [addTaskId]: { taskId: addTaskId, title: task.title, proposedStartLocal: addTimeLocal } }));
    setAddTaskId('');
    setAddTimeLocal('');
    setIsAdding(false);
  }

  function removePendingAdd(taskId: string) {
    setPendingAdds((prev) => {
      const { [taskId]: _omit, ...rest } = prev;
      return rest;
    });
  }

  function startEditing(change: PlanChange) {
    setEditingTaskId(null); // mutually exclusive with the task-details editor
    setTaskDraft(null);
    setEditingChangeId(change.id);
    const existingLocal = pendingEdits[change.id]?.proposedStartLocal;
    if (!existingLocal) {
      // Seed the input with the currently-effective time — which is the
      // AI's original proposal unless this row already has an unsaved
      // local edit from earlier in this same session.
      setPendingEdits((prev) => ({
        ...prev,
        [change.id]: { ...prev[change.id], proposedStartLocal: toDatetimeLocalValue(change.proposedStart) },
      }));
    }
  }

  function toggleRemove(changeId: string) {
    setPendingEdits((prev) => {
      const current = prev[changeId];
      if (current?.remove) {
        // Undo — drop the pending edit entirely rather than leaving a
        // no-op entry behind.
        const { [changeId]: _omit, ...rest } = prev;
        return rest;
      }
      return { ...prev, [changeId]: { remove: true } };
    });
    if (editingChangeId === changeId) setEditingChangeId(null);
  }

  const isPending = latestPlanRun?.status === 'PROPOSED';
  const hasPendingEdits = Object.keys(pendingEdits).length > 0 || Object.keys(pendingAdds).length > 0;

  return (
    <div
      data-testid="daily-plan-card"
      className="mx-4 mb-3 rounded-card border border-border dark:border-border-dark bg-surface dark:bg-surface-dark p-4"
    >
      {error && <p className="mb-2 text-xs text-danger dark:text-danger-dark" role="alert">{error}</p>}

      {isPending && latestPlanRun ? (
        <div className="flex flex-col gap-3">
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h2 className="text-sm font-medium text-text-primary dark:text-text-primary-dark">Proposed plan</h2>
              {isAutoGenerated(latestPlanRun.triggerEvent) && (
                <span className="rounded-full border border-border dark:border-border-dark px-1.5 py-0.5 text-xs text-text-secondary dark:text-text-secondary-dark">
                  Auto-generated
                </span>
              )}
            </div>
            <p className="mt-1 text-xs text-text-secondary dark:text-text-secondary-dark">
              {latestPlanRun.diff.summary}
            </p>
            {latestPlanRun.autoApplyAt && (
              <p role="status" className="mt-1 text-xs font-medium text-accent dark:text-accent-dark">
                {formatAutoApplyNotice(latestPlanRun.autoApplyAt)}
              </p>
            )}
          </div>

          {latestPlanRun.diff.changes.length > 0 && (
            <div className="flex flex-col gap-2">
              {latestPlanRun.diff.changes.map((change) => {
                const pending = pendingEdits[change.id];
                const isRemoved = !!pending?.remove;
                const isEditingThis = editingChangeId === change.id;
                const isEditingTaskDetails = editingTaskId === change.id;
                const effectiveTime =
                  pending?.proposedStartLocal && !isRemoved
                    ? formatTime(fromDatetimeLocalValue(pending.proposedStartLocal))
                    : formatTime(change.proposedStart);
                const wasEdited = !!pending?.proposedStartLocal && !isRemoved;

                return (
                  <div
                    key={change.id}
                    className={`rounded-control bg-background dark:bg-background-dark px-3 py-2 ${
                      isRemoved ? 'opacity-50' : ''
                    }`}
                  >
                    {isRemoved ? (
                      <div className="flex items-center justify-between gap-2">
                        <p className="text-sm text-text-secondary dark:text-text-secondary-dark line-through">
                          {formatTime(change.proposedStart)} — {change.task.title}
                        </p>
                        <button
                          onClick={() => toggleRemove(change.id)}
                          className="shrink-0 text-xs font-medium text-accent"
                        >
                          Undo
                        </button>
                      </div>
                    ) : isEditingThis ? (
                      <div className="flex flex-col gap-2">
                        <p className="text-sm text-text-primary dark:text-text-primary-dark">{change.task.title}</p>
                        <input
                          type="datetime-local"
                          value={pending?.proposedStartLocal ?? toDatetimeLocalValue(change.proposedStart)}
                          onChange={(e) =>
                            setPendingEdits((prev) => ({
                              ...prev,
                              [change.id]: { ...prev[change.id], proposedStartLocal: e.target.value },
                            }))
                          }
                          aria-label={`Proposed start time for "${change.task.title}"`}
                          className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                        />
                        <button
                          onClick={() => setEditingChangeId(null)}
                          className="self-start text-xs font-medium text-accent"
                        >
                          Done
                        </button>
                      </div>
                    ) : isEditingTaskDetails && taskDraft ? (
                      // Editing a task's own details increment: unlike the
                      // time editor above, "Save" here writes the task
                      // immediately (updateTask), not just local state — a
                      // title/priority/duration change is a real edit to
                      // the task itself regardless of what happens to this
                      // plan.
                      <div className="flex flex-col gap-2">
                        <input
                          type="text"
                          value={taskDraft.title}
                          onChange={(e) => setTaskDraft({ ...taskDraft, title: e.target.value })}
                          aria-label="Task title"
                          className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                        />
                        <div className="flex gap-2">
                          <select
                            value={taskDraft.priority}
                            onChange={(e) => setTaskDraft({ ...taskDraft, priority: parseInt(e.target.value, 10) })}
                            aria-label="Priority"
                            className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                          >
                            <option value={1}>Priority: Urgent</option>
                            <option value={2}>Priority: High</option>
                            <option value={3}>Priority: Normal</option>
                            <option value={4}>Priority: Someday</option>
                          </select>
                          <input
                            type="number"
                            min={1}
                            value={taskDraft.estimatedDurationMinutes}
                            onChange={(e) =>
                              setTaskDraft({ ...taskDraft, estimatedDurationMinutes: parseInt(e.target.value, 10) || 1 })
                            }
                            aria-label="Estimated duration in minutes"
                            className="w-20 rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                          />
                          <span className="self-center text-xs text-text-secondary dark:text-text-secondary-dark">min</span>
                        </div>
                        {taskSaveError && <p className="text-xs text-danger dark:text-danger-dark" role="alert">{taskSaveError}</p>}
                        <div className="flex gap-2">
                          <button
                            disabled={savingTaskDetails}
                            onClick={() => handleSaveTaskDetails(change)}
                            className="text-xs font-medium text-accent disabled:opacity-50"
                          >
                            {savingTaskDetails ? 'Saving…' : 'Save task'}
                          </button>
                          <button
                            onClick={() => {
                              setEditingTaskId(null);
                              setTaskDraft(null);
                              setTaskSaveError(null);
                            }}
                            className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                          >
                            Cancel
                          </button>
                        </div>
                      </div>
                    ) : (
                      <>
                        <div className="flex items-center justify-between gap-2">
                          <p className="text-sm text-text-primary dark:text-text-primary-dark">
                            <span className="font-medium">{effectiveTime}</span> — {change.task.title}
                            {wasEdited && (
                              <span className="ml-1 text-xs text-accent">(edited)</span>
                            )}
                          </p>
                        </div>
                        <div className="mt-1 flex items-center justify-between gap-2">
                          <p className="text-xs text-text-secondary dark:text-text-secondary-dark">{change.reason}</p>
                          <div className="flex shrink-0 gap-2">
                            <button
                              onClick={() => startEditing(change)}
                              className="text-xs font-medium text-accent"
                            >
                              Edit time
                            </button>
                            <button
                              onClick={() => startEditingTask(change)}
                              className="text-xs font-medium text-accent"
                            >
                              Edit task
                            </button>
                            <button
                              onClick={() => toggleRemove(change.id)}
                              className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                            >
                              Remove
                            </button>
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          )}

          {/* Free-form plan editing increment: tasks staged via "Add a task"
              below, shown the same way an AI-proposed change is, but
              distinguished with an "(added)" label since there's no
              PlanChange.reason to show for something the person picked
              themselves. */}
          {Object.values(pendingAdds).length > 0 && (
            <div className="flex flex-col gap-2">
              {Object.values(pendingAdds).map((add) => (
                <div
                  key={add.taskId}
                  className="rounded-control bg-background dark:bg-background-dark px-3 py-2"
                >
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm text-text-primary dark:text-text-primary-dark">
                      <span className="font-medium">{formatTime(fromDatetimeLocalValue(add.proposedStartLocal))}</span>{' '}
                      — {add.title} <span className="ml-1 text-xs text-accent">(added)</span>
                    </p>
                    <button
                      onClick={() => removePendingAdd(add.taskId)}
                      className="shrink-0 text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Free-form plan editing increment: lets a person put one of
              their own open tasks onto the plan even if the AI never
              suggested it — the plan card's only entry point for that,
              since the AI-proposed rows above can only be moved or dropped,
              never created from nothing. */}
          {availableTasksToAdd.length > 0 &&
            (isAdding ? (
              <div className="flex flex-col gap-2 rounded-control border border-border dark:border-border-dark px-3 py-2">
                <select
                  value={addTaskId}
                  onChange={(e) => setAddTaskId(e.target.value)}
                  aria-label="Task to add"
                  className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                >
                  <option value="">Pick a task…</option>
                  {availableTasksToAdd.map((t) => (
                    <option key={t.id} value={t.id}>
                      {t.title}
                    </option>
                  ))}
                </select>
                <input
                  type="datetime-local"
                  value={addTimeLocal}
                  onChange={(e) => setAddTimeLocal(e.target.value)}
                  aria-label="Start time for the new task"
                  className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                />
                <div className="flex gap-2">
                  <button
                    onClick={handleAddTask}
                    disabled={!addTaskId || !addTimeLocal}
                    className="text-xs font-medium text-accent disabled:opacity-50"
                  >
                    Add to plan
                  </button>
                  <button
                    onClick={() => {
                      setIsAdding(false);
                      setAddTaskId('');
                      setAddTimeLocal('');
                    }}
                    className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <button onClick={() => setIsAdding(true)} className="self-start text-xs font-medium text-accent">
                + Add a task
              </button>
            ))}

          {hasPendingEdits ? (
            <div className="flex flex-col gap-2">
              <div className="flex gap-2">
                <button
                  disabled={responding}
                  onClick={handleSaveEdits}
                  className="flex-1 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
                >
                  {responding ? 'Saving…' : 'Save & apply changes'}
                </button>
                <button
                  disabled={responding}
                  onClick={resetLocalEditState}
                  className="flex-1 rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-secondary dark:text-text-secondary-dark disabled:opacity-50"
                >
                  Discard edits
                </button>
              </div>
            </div>
          ) : (
            <div className="flex gap-2">
              <button
                disabled={responding}
                onClick={() => handleRespond('ACCEPT')}
                className="flex-1 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
              >
                {responding ? 'Saving…' : 'Accept plan'}
              </button>
              <button
                disabled={responding}
                onClick={() => handleRespond('REJECT')}
                className="flex-1 rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-secondary dark:text-text-secondary-dark disabled:opacity-50"
              >
                Reject
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="flex items-center gap-3">
          {/* Sleek/futuristic visual redesign (2026-09-01): Nova stands in
              for "the assistant is here, ready when you are" — steady-state
              only, not shown in the pending-proposal branch above, since
              that state already has the diff/accept/reject UI doing the
              talking. */}
          <NovaAvatar size={34} />
          <p className="flex-1 text-sm text-text-secondary dark:text-text-secondary-dark">
            {latestPlanRun?.status === 'ACCEPTED'
              ? 'Your last plan was applied. Ask again anytime your day changes.'
              : latestPlanRun?.status === 'EDITED'
                ? 'Your last plan was applied with your edits. Ask again anytime your day changes.'
                : 'Let AI propose times for your open tasks based on your day and how you’re feeling.'}
            {(latestPlanRun?.status === 'ACCEPTED' || latestPlanRun?.status === 'EDITED') &&
              isAutoGenerated(latestPlanRun.triggerEvent) && (
                <span className="ml-1.5 rounded-full border border-border dark:border-border-dark px-1.5 py-0.5 text-xs text-text-secondary dark:text-text-secondary-dark">
                  Auto-generated
                </span>
              )}
          </p>
          <button
            disabled={generating}
            onClick={handleGenerate}
            className="shrink-0 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
          >
            {generating ? 'Thinking…' : 'Generate my plan'}
          </button>
        </div>
      )}
    </div>
  );
}
