'use client';

import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import { Capacitor } from '@capacitor/core';
import {
  REGISTER_PUSH_SUBSCRIPTION,
  SEND_TEST_NOTIFICATION,
  UNREGISTER_PUSH_SUBSCRIPTION,
  VAPID_PUBLIC_KEY_QUERY,
} from '../lib/queries';

// Real notification delivery increment. The `urlBase64ToUint8Array` step is
// unavoidable boilerplate every Web Push implementation needs — the Push
// API's `applicationServerKey` option requires a raw Uint8Array, but VAPID
// keys are handed around (and generated by `web-push`) as base64url strings.
function urlBase64ToUint8Array(base64Url: string): Uint8Array {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
}

type Status = 'unknown' | 'unsupported' | 'native' | 'unconfigured' | 'off' | 'on' | 'denied';

// Self-contained subscribe/unsubscribe control — deliberately not tied to
// the pushNotificationsEnabled preference above it on this page, which only
// ever controlled *in-app* delivery (see NotificationsService's schema
// comment). Browser push additionally needs this device's own explicit
// permission grant and a live PushManager subscription, which is a genuinely
// separate, per-browser piece of state no preference toggle can capture.
export function PushSubscribeButton() {
  const [status, setStatus] = useState<Status>('unknown');
  const [error, setError] = useState<string | null>(null);
  const [testResult, setTestResult] = useState<string | null>(null);
  const { data: vapidData } = useQuery(VAPID_PUBLIC_KEY_QUERY);
  const [registerSubscription, { loading: registering }] = useMutation(REGISTER_PUSH_SUBSCRIPTION);
  const [unregisterSubscription, { loading: unregistering }] = useMutation(UNREGISTER_PUSH_SUBSCRIPTION);
  const [sendTestNotification, { loading: sendingTest }] = useMutation(SEND_TEST_NOTIFICATION);

  useEffect(() => {
    let cancelled = false;

    async function checkExisting() {
      // Native app shell increment: inside the Capacitor app, browser push
      // is genuinely unavailable (Android's WebView has no Push API at
      // all — see NativePushRegistration.tsx's own comment), but that's not
      // this device's fault or something a person here needs to "enable" —
      // NativePushRegistration already handles it automatically, silently,
      // via FCM. Checked first, before the generic unsupported branch
      // below, so the native app gets its own accurate message instead of
      // the browser-facing one.
      if (typeof window !== 'undefined' && Capacitor.isNativePlatform()) {
        if (!cancelled) setStatus('native');
        return;
      }
      if (typeof window === 'undefined' || !('serviceWorker' in navigator) || !('PushManager' in window)) {
        if (!cancelled) setStatus('unsupported');
        return;
      }
      if (Notification.permission === 'denied') {
        if (!cancelled) setStatus('denied');
        return;
      }
      try {
        const registration = await navigator.serviceWorker.ready;
        const existing = await registration.pushManager.getSubscription();
        if (!cancelled) setStatus(existing ? 'on' : 'off');
      } catch {
        if (!cancelled) setStatus('off');
      }
    }

    checkExisting();
    return () => {
      cancelled = true;
    };
  }, []);

  const vapidPublicKey: string | null = vapidData?.vapidPublicKey ?? null;

  if (status === 'unknown') return null;

  if (status === 'native') {
    return (
      <p className="mb-3 text-xs text-text-secondary dark:text-text-secondary-dark">
        Notifications for this app are turned on automatically — no separate step needed here.
      </p>
    );
  }

  if (status === 'unsupported') {
    return (
      <p className="mb-3 text-xs text-text-secondary dark:text-text-secondary-dark">
        Browser notifications aren&apos;t supported on this device.
      </p>
    );
  }

  if (!vapidPublicKey && status !== 'on') {
    // Backend has no VAPID keys configured — same "quietly unavailable, not
    // an error" treatment WebPushService itself gives an unconfigured
    // server (isConfigured() gate, no-op otherwise).
    return null;
  }

  if (status === 'denied') {
    return (
      <p className="mb-3 text-xs text-text-secondary dark:text-text-secondary-dark">
        Browser notifications are blocked for this site. Enable them in your browser&apos;s site settings to turn
        this on.
      </p>
    );
  }

  async function enable() {
    setError(null);
    try {
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        setStatus(permission === 'denied' ? 'denied' : 'off');
        return;
      }

      const registration = await navigator.serviceWorker.ready;

      // Races the real subscribe() call against a 10s timer so a hang on
      // the browser's real, out-of-page push service (which never shows up
      // in a Playwright page-level network trace — that traffic never goes
      // through the page's own fetch/XHR/resource layer at all) fails
      // loudly through the same catch block below instead of leaving the
      // button stuck on "Enabling…" indefinitely with no way out.
      //
      // Fix (frontend audit, 2026-08-25): this block, and every other step
      // in this function, used to also log its own progress via
      // `console.log('[PUSH DEBUG] ...')` — nine call sites in total,
      // originally added to debug the exact hang this timeout now guards
      // against (see git history). Left in past that point, they were pure
      // noise on every real subscribe — worse, one of them
      // (`subscribe() resolved ... endpoint=...`) logged the subscription's
      // real push endpoint URL, a value that uniquely identifies this
      // device's push channel, into the browser's devtools console on every
      // successful enable. Removed; the timeout/error-catch structure below
      // still gives a developer a real signal (via the `console.error` in
      // the `catch` block) without logging on every success.
      const subscription = await Promise.race([
        registration.pushManager.subscribe({
          userVisibleOnly: true,
          // `as BufferSource` — a newer TypeScript/lib.dom.d.ts pairing than
          // this file was originally written against tightened
          // `ArrayBufferLike` (adding resizable-ArrayBuffer members
          // `SharedArrayBuffer` doesn't have), which makes a plain
          // `Uint8Array` no longer structurally assignable to
          // `BufferSource` even though this is exactly what the real Push
          // API expects and has always accepted at runtime — a typing-only
          // friction point, not a real bug, so a narrow cast here is
          // correct rather than papering over anything.
          applicationServerKey: urlBase64ToUint8Array(vapidPublicKey as string) as BufferSource,
        }),
        new Promise<never>((_, reject) =>
          setTimeout(() => reject(new Error('Push subscription timed out after 10s')), 10_000),
        ),
      ]);
      const json = subscription.toJSON();

      const { data } = await registerSubscription({
        variables: {
          input: { endpoint: json.endpoint, p256dh: json.keys?.p256dh, auth: json.keys?.auth },
        },
      });

      if (!data?.registerPushSubscription?.registered) {
        setError("We couldn't enable browser notifications. Try again.");
        return;
      }
      setStatus('on');
    } catch (err) {
      // Logged, not swallowed — a bare catch with no trace of what actually
      // failed (permission plumbing, the real Push API rejecting the
      // subscribe call, the registerSubscription mutation itself) is a real
      // diagnosability gap for anyone debugging this in the field, not just
      // in tests. The person-facing message stays generic; this is for
      // whoever's looking at devtools.
      // eslint-disable-next-line no-console
      console.error('Failed to enable browser notifications:', err);
      setError("We couldn't enable browser notifications. Try again.");
    }
  }

  // On-demand diagnostic increment (2026-08-19, explicit user request): lets
  // someone confirm right now whether a real push actually reaches *this*
  // device, instead of waiting for the next naturally-scheduled reminder to
  // find out. See push.resolver.ts's sendTestNotification for why this is
  // a separate, side-effect-free mutation rather than reusing any real
  // reminder path.
  async function sendTest() {
    setTestResult(null);
    try {
      const { data } = await sendTestNotification();
      const result = data?.sendTestNotification;
      if (result?.errors?.length) {
        setTestResult(result.errors[0].message);
      } else if (!result?.sent) {
        setTestResult("No subscription found for this device — try turning notifications off and on again above.");
      } else {
        setTestResult('Test notification sent — check for it now.');
      }
    } catch {
      setTestResult("We couldn't send a test notification. Try again.");
    }
  }

  async function disable() {
    setError(null);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await unregisterSubscription({ variables: { endpoint: subscription.endpoint } });
        await subscription.unsubscribe();
      }
      setStatus('off');
    } catch {
      setError("We couldn't turn off browser notifications. Try again.");
    }
  }

  const busy = registering || unregistering;

  return (
    <div className="mb-3 flex flex-wrap items-center gap-3">
      <button
        onClick={status === 'on' ? disable : enable}
        disabled={busy}
        className="rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-primary dark:text-text-primary-dark disabled:opacity-50"
      >
        {busy ? 'Working…' : status === 'on' ? 'Turn off browser notifications' : 'Turn on browser notifications'}
      </button>
      {/* Only shown once this device is actually subscribed — testing
          before that would just re-report the same "nothing registered"
          state the main button above already communicates. */}
      {status === 'on' && (
        <button
          onClick={sendTest}
          disabled={sendingTest}
          className="rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-primary dark:text-text-primary-dark disabled:opacity-50"
        >
          {sendingTest ? 'Sending…' : 'Send test notification'}
        </button>
      )}
      {error && <span className="text-xs text-danger dark:text-danger-dark" role="alert">{error}</span>}
      {testResult && (
        <span className="text-xs text-text-secondary dark:text-text-secondary-dark" role="status">
          {testResult}
        </span>
      )}
    </div>
  );
}
