'use client';

import { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import { REGISTER_PUSH_SUBSCRIPTION, UNREGISTER_PUSH_SUBSCRIPTION, VAPID_PUBLIC_KEY_QUERY } from '../lib/queries';

// Real notification delivery increment. The `urlBase64ToUint8Array` step is
// unavoidable boilerplate every Web Push implementation needs — the Push
// API's `applicationServerKey` option requires a raw Uint8Array, but VAPID
// keys are handed around (and generated by `web-push`) as base64url strings.
function urlBase64ToUint8Array(base64Url: string): Uint8Array {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  return Uint8Array.from([...rawData].map((char) => char.charCodeAt(0)));
}

type Status = 'unknown' | 'unsupported' | 'unconfigured' | 'off' | 'on' | 'denied';

// Self-contained subscribe/unsubscribe control — deliberately not tied to
// the pushNotificationsEnabled preference above it on this page, which only
// ever controlled *in-app* delivery (see NotificationsService's schema
// comment). Browser push additionally needs this device's own explicit
// permission grant and a live PushManager subscription, which is a genuinely
// separate, per-browser piece of state no preference toggle can capture.
export function PushSubscribeButton() {
  const [status, setStatus] = useState<Status>('unknown');
  const [error, setError] = useState<string | null>(null);
  const { data: vapidData } = useQuery(VAPID_PUBLIC_KEY_QUERY);
  const [registerSubscription, { loading: registering }] = useMutation(REGISTER_PUSH_SUBSCRIPTION);
  const [unregisterSubscription, { loading: unregistering }] = useMutation(UNREGISTER_PUSH_SUBSCRIPTION);

  useEffect(() => {
    let cancelled = false;

    async function checkExisting() {
      if (typeof window === 'undefined' || !('serviceWorker' in navigator) || !('PushManager' in window)) {
        if (!cancelled) setStatus('unsupported');
        return;
      }
      if (Notification.permission === 'denied') {
        if (!cancelled) setStatus('denied');
        return;
      }
      try {
        const registration = await navigator.serviceWorker.ready;
        const existing = await registration.pushManager.getSubscription();
        if (!cancelled) setStatus(existing ? 'on' : 'off');
      } catch {
        if (!cancelled) setStatus('off');
      }
    }

    checkExisting();
    return () => {
      cancelled = true;
    };
  }, []);

  const vapidPublicKey: string | null = vapidData?.vapidPublicKey ?? null;

  if (status === 'unknown') return null;

  if (status === 'unsupported') {
    return (
      <p className="mb-3 text-xs text-text-secondary dark:text-text-secondary-dark">
        Browser notifications aren&apos;t supported on this device.
      </p>
    );
  }

  if (!vapidPublicKey && status !== 'on') {
    // Backend has no VAPID keys configured — same "quietly unavailable, not
    // an error" treatment WebPushService itself gives an unconfigured
    // server (isConfigured() gate, no-op otherwise).
    return null;
  }

  if (status === 'denied') {
    return (
      <p className="mb-3 text-xs text-text-secondary dark:text-text-secondary-dark">
        Browser notifications are blocked for this site. Enable them in your browser&apos;s site settings to turn
        this on.
      </p>
    );
  }

  async function enable() {
    setError(null);
    try {
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] enable() start, vapidPublicKey present=', !!vapidPublicKey);
      const permission = await Notification.requestPermission();
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] requestPermission resolved:', permission);
      if (permission !== 'granted') {
        setStatus(permission === 'denied' ? 'denied' : 'off');
        return;
      }

      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] awaiting serviceWorker.ready...');
      const registration = await navigator.serviceWorker.ready;
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] serviceWorker.ready resolved, scope=', registration.scope, 'active=', !!registration.active);

      // TEMPORARY diagnostic — races the real subscribe() call against a
      // 10s timer so a hang on the browser's real, out-of-page push
      // service (which never shows up in a Playwright page-level network
      // trace — that traffic never goes through the page's own
      // fetch/XHR/resource layer at all) prints unambiguous evidence
      // instead of leaving a silent 15s locator timeout as the only clue.
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] calling pushManager.subscribe()...');
      const subscribeStarted = Date.now();
      const subscription = await Promise.race([
        registration.pushManager.subscribe({
          userVisibleOnly: true,
          // `as BufferSource` — a newer TypeScript/lib.dom.d.ts pairing than
          // this file was originally written against tightened
          // `ArrayBufferLike` (adding resizable-ArrayBuffer members
          // `SharedArrayBuffer` doesn't have), which makes a plain
          // `Uint8Array` no longer structurally assignable to
          // `BufferSource` even though this is exactly what the real Push
          // API expects and has always accepted at runtime — a typing-only
          // friction point, not a real bug, so a narrow cast here is
          // correct rather than papering over anything.
          applicationServerKey: urlBase64ToUint8Array(vapidPublicKey as string) as BufferSource,
        }),
        new Promise<never>((_, reject) =>
          setTimeout(() => {
            // eslint-disable-next-line no-console
            console.log('[PUSH DEBUG] pushManager.subscribe() still pending after 10s');
            reject(new Error('[PUSH DEBUG] subscribe() timed out after 10s'));
          }, 10_000),
        ),
      ]);
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] subscribe() resolved after', Date.now() - subscribeStarted, 'ms, endpoint=', subscription.endpoint);
      const json = subscription.toJSON();

      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] calling registerSubscription mutation...');
      const { data } = await registerSubscription({
        variables: {
          input: { endpoint: json.endpoint, p256dh: json.keys?.p256dh, auth: json.keys?.auth },
        },
      });
      // eslint-disable-next-line no-console
      console.log('[PUSH DEBUG] registerSubscription resolved:', data);

      if (!data?.registerPushSubscription?.registered) {
        setError("We couldn't enable browser notifications. Try again.");
        return;
      }
      setStatus('on');
    } catch (err) {
      // Logged, not swallowed — a bare catch with no trace of what actually
      // failed (permission plumbing, the real Push API rejecting the
      // subscribe call, the registerSubscription mutation itself) is a real
      // diagnosability gap for anyone debugging this in the field, not just
      // in tests. The person-facing message stays generic; this is for
      // whoever's looking at devtools.
      // eslint-disable-next-line no-console
      console.error('Failed to enable browser notifications:', err);
      setError("We couldn't enable browser notifications. Try again.");
    }
  }

  async function disable() {
    setError(null);
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      if (subscription) {
        await unregisterSubscription({ variables: { endpoint: subscription.endpoint } });
        await subscription.unsubscribe();
      }
      setStatus('off');
    } catch {
      setError("We couldn't turn off browser notifications. Try again.");
    }
  }

  const busy = registering || unregistering;

  return (
    <div className="mb-3 flex items-center gap-3">
      <button
        onClick={status === 'on' ? disable : enable}
        disabled={busy}
        className="rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-primary dark:text-text-primary-dark disabled:opacity-50"
      >
        {busy ? 'Working…' : status === 'on' ? 'Turn off browser notifications' : 'Turn on browser notifications'}
      </button>
      {error && <span className="text-xs text-danger dark:text-danger-dark" role="alert">{error}</span>}
    </div>
  );
}
