'use client';

import { useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import { LATEST_PLAN_RUN_QUERY, REQUEST_REPLAN_SCOPED, RESPOND_TO_PLAN_RUN, UPDATE_TASK } from '../lib/queries';
import { fromDatetimeLocalValue, toDatetimeLocalValue } from '../lib/datetime-local';

type Scope = 'WEEK' | 'MONTH';

interface PlanChange {
  id: string;
  proposedStart: string;
  reason: string;
  task: { id: string; title: string; priority: number; estimatedDurationMinutes?: number | null };
}

// Free-form plan editing increment: see AiPlanCard's identical OpenTask.
interface OpenTask {
  id: string;
  title: string;
}

// See AiPlanCard's own PendingEdit for the full reasoning — identical
// shape, duplicated here rather than shared, since these two cards already
// don't share component code (separate cards for separate scopes, see the
// comment below).
interface PendingEdit {
  proposedStartLocal?: string;
  remove?: boolean;
}

// Free-form plan editing increment: see AiPlanCard's identical PendingAdd.
interface PendingAdd {
  taskId: string;
  title: string;
  proposedStartLocal: string;
}

// Editing a task's own details increment: see AiPlanCard's identical
// TaskDraft.
interface TaskDraft {
  title: string;
  priority: number;
  estimatedDurationMinutes: number;
}

// Auto-plan indicator increment: see AiPlanCard's identical helper for the
// full reasoning — duplicated rather than shared, same "these two cards
// already don't share component code" precedent as PendingEdit/PendingAdd/
// TaskDraft above.
function isAutoGenerated(triggerEvent: string | undefined | null): boolean {
  return !!triggerEvent?.startsWith('auto_');
}

function formatDateTime(iso: string) {
  return new Date(iso).toLocaleString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

// Morning plan auto-apply increment (2026-09-05) — same notice/logic as
// AiPlanCard's own formatAutoApplyNotice, deliberately duplicated here
// rather than shared: these two components already don't share any state
// or types (each tracks its own PlanRun query independently — see this
// file's own top comment), and this is small and self-contained enough
// that a shared import isn't worth the coupling.
function formatAutoApplyNotice(autoApplyAt: string): string {
  const target = new Date(autoApplyAt).getTime();
  const minutesLeft = Math.round((target - Date.now()) / 60000);
  const clockTime = new Date(autoApplyAt).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
  if (minutesLeft <= 0) return 'Applying automatically any moment now, unless you make a change first.';
  if (minutesLeft < 60) return `Auto-applies in ${minutesLeft} min (at ${clockTime}) unless you make a change first.`;
  const hours = Math.floor(minutesLeft / 60);
  const mins = minutesLeft % 60;
  const hoursLabel = mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
  return `Auto-applies in ${hoursLabel} (at ${clockTime}) unless you make a change first.`;
}

// Weekly/monthly AI plan generation increment (PRD §7.4) — same propose/
// accept/reject/edit shape as AiPlanCard (same requestReplan/
// respondToPlanRun mutations, just with $scope set), but its own card since
// a multi-day plan needs date-and-time labels, not just time, and a
// Week/Month toggle AiPlanCard has no equivalent of. Each scope tracks its
// own latest plan run independently (separate query variables per scope,
// not shared state) since a proposed week plan and a proposed month plan
// are genuinely different things a person might have pending at once.
// Editing a proposed AI plan increment: same per-change edit/remove flow as
// AiPlanCard, extended here too since PlannerService.respondToPlanRun's
// EDIT branch is scope-aware (it re-validates against the right window and
// working-hours check for whichever scope this plan run actually is).
export function WeeklyPlanCard({ openTasks = [] }: { openTasks?: OpenTask[] }) {
  const [scope, setScope] = useState<Scope>('WEEK');
  const [error, setError] = useState<string | null>(null);
  const [pendingEdits, setPendingEdits] = useState<Record<string, PendingEdit>>({});
  const [editingChangeId, setEditingChangeId] = useState<string | null>(null);
  // Free-form plan editing increment.
  const [pendingAdds, setPendingAdds] = useState<Record<string, PendingAdd>>({});
  const [isAdding, setIsAdding] = useState(false);
  const [addTaskId, setAddTaskId] = useState('');
  const [addTimeLocal, setAddTimeLocal] = useState('');
  // Editing a task's own details increment.
  const [editingTaskId, setEditingTaskId] = useState<string | null>(null);
  const [taskDraft, setTaskDraft] = useState<TaskDraft | null>(null);
  const [taskSaveError, setTaskSaveError] = useState<string | null>(null);

  const { data, loading: querying } = useQuery(LATEST_PLAN_RUN_QUERY, { variables: { scope } });
  const refetchQueries = [{ query: LATEST_PLAN_RUN_QUERY, variables: { scope } }];

  const [requestReplan, { loading: generating }] = useMutation(REQUEST_REPLAN_SCOPED, { refetchQueries });
  const [respond, { loading: responding }] = useMutation(RESPOND_TO_PLAN_RUN, { refetchQueries });
  const [updateTask, { loading: savingTaskDetails }] = useMutation(UPDATE_TASK, { refetchQueries });

  const planRun = data?.latestPlanRun;
  const isPending = planRun?.status === 'PROPOSED';
  const scopeLabel = scope === 'WEEK' ? 'week' : 'month';
  const hasPendingEdits = Object.keys(pendingEdits).length > 0 || Object.keys(pendingAdds).length > 0;

  function resetLocalEditState() {
    setPendingEdits({});
    setEditingChangeId(null);
    setPendingAdds({});
    setIsAdding(false);
    setAddTaskId('');
    setAddTimeLocal('');
    setEditingTaskId(null);
    setTaskDraft(null);
    setTaskSaveError(null);
  }

  // See AiPlanCard's identical startEditingTask/handleSaveTaskDetails for
  // the full reasoning.
  function startEditingTask(change: PlanChange) {
    setEditingChangeId(null);
    setEditingTaskId(change.id);
    setTaskSaveError(null);
    setTaskDraft({
      title: change.task.title,
      priority: change.task.priority,
      estimatedDurationMinutes: change.task.estimatedDurationMinutes ?? 30,
    });
  }

  async function handleSaveTaskDetails(change: PlanChange) {
    if (!taskDraft) return;
    setTaskSaveError(null);
    const result = await updateTask({
      variables: {
        id: change.task.id,
        input: {
          title: taskDraft.title,
          priority: taskDraft.priority,
          estimatedDurationMinutes: taskDraft.estimatedDurationMinutes,
        },
      },
    });
    const payload = result.data?.updateTask;
    if (payload?.errors?.length) {
      setTaskSaveError(payload.errors[0].message);
      return;
    }
    setPendingEdits((prev) => ({ ...prev, [change.id]: { ...prev[change.id] } }));
    setEditingTaskId(null);
    setTaskDraft(null);
  }

  function switchScope(next: Scope) {
    setScope(next);
    resetLocalEditState();
    setError(null);
  }

  async function handleGenerate() {
    setError(null);
    resetLocalEditState();
    const result = await requestReplan({ variables: { scope } });
    const payload = result.data?.requestReplan;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    }
  }

  async function handleRespond(decision: 'ACCEPT' | 'REJECT') {
    if (!planRun) return;
    setError(null);
    const result = await respond({ variables: { id: planRun.id, decision } });
    const payload = result.data?.respondToPlanRun;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    } else {
      resetLocalEditState();
    }
  }

  async function handleSaveEdits() {
    if (!planRun) return;
    setError(null);
    const edits = Object.entries(pendingEdits).map(([changeId, edit]) => ({
      changeId,
      remove: edit.remove ?? false,
      proposedStart: edit.remove || !edit.proposedStartLocal ? undefined : fromDatetimeLocalValue(edit.proposedStartLocal),
    }));
    // Free-form plan editing increment.
    const adds = Object.values(pendingAdds).map((add) => ({
      taskId: add.taskId,
      proposedStart: fromDatetimeLocalValue(add.proposedStartLocal),
    }));
    const result = await respond({ variables: { id: planRun.id, decision: 'EDIT', edits, adds } });
    const payload = result.data?.respondToPlanRun;
    if (payload?.errors?.length) {
      setError(payload.errors[0].message);
    } else {
      resetLocalEditState();
    }
  }

  // Free-form plan editing increment: see AiPlanCard's identical reasoning.
  const plannedTaskIds = new Set([
    ...((planRun?.diff.changes.map((c: PlanChange) => c.task?.id).filter(Boolean) as string[]) ?? []),
    ...Object.keys(pendingAdds),
  ]);
  const availableTasksToAdd = openTasks.filter((t) => !plannedTaskIds.has(t.id));

  function handleAddTask() {
    if (!addTaskId || !addTimeLocal) return;
    const task = openTasks.find((t) => t.id === addTaskId);
    if (!task) return;
    setPendingAdds((prev) => ({ ...prev, [addTaskId]: { taskId: addTaskId, title: task.title, proposedStartLocal: addTimeLocal } }));
    setAddTaskId('');
    setAddTimeLocal('');
    setIsAdding(false);
  }

  function removePendingAdd(taskId: string) {
    setPendingAdds((prev) => {
      const { [taskId]: _omit, ...rest } = prev;
      return rest;
    });
  }

  function startEditing(change: PlanChange) {
    setEditingTaskId(null);
    setTaskDraft(null);
    setEditingChangeId(change.id);
    const existingLocal = pendingEdits[change.id]?.proposedStartLocal;
    if (!existingLocal) {
      setPendingEdits((prev) => ({
        ...prev,
        [change.id]: { ...prev[change.id], proposedStartLocal: toDatetimeLocalValue(change.proposedStart) },
      }));
    }
  }

  function toggleRemove(changeId: string) {
    setPendingEdits((prev) => {
      const current = prev[changeId];
      if (current?.remove) {
        const { [changeId]: _omit, ...rest } = prev;
        return rest;
      }
      return { ...prev, [changeId]: { remove: true } };
    });
    if (editingChangeId === changeId) setEditingChangeId(null);
  }

  return (
    <div className="mx-4 mb-3 rounded-card border border-border dark:border-border-dark bg-surface dark:bg-surface-dark p-4">
      <div className="mb-3 flex items-center justify-between">
        <h2 className="text-sm font-medium text-text-primary dark:text-text-primary-dark">Longer-range plan</h2>
        <div className="flex gap-1 rounded-control border border-border dark:border-border-dark p-0.5">
          {(['WEEK', 'MONTH'] as Scope[]).map((s) => (
            <button
              key={s}
              onClick={() => switchScope(s)}
              aria-pressed={scope === s}
              className={`rounded-control px-2 py-1 text-xs ${
                scope === s ? 'bg-accent text-white' : 'text-text-secondary dark:text-text-secondary-dark'
              }`}
            >
              {s === 'WEEK' ? 'Week' : 'Month'}
            </button>
          ))}
        </div>
      </div>

      {error && <p className="mb-2 text-xs text-danger dark:text-danger-dark" role="alert">{error}</p>}

      {isPending && planRun ? (
        <div className="flex flex-col gap-3">
          {isAutoGenerated(planRun.triggerEvent) && (
            <span className="self-start rounded-full border border-border dark:border-border-dark px-1.5 py-0.5 text-xs text-text-secondary dark:text-text-secondary-dark">
              Auto-generated
            </span>
          )}
          <p className="text-xs text-text-secondary dark:text-text-secondary-dark">{planRun.diff.summary}</p>
          {planRun.autoApplyAt && (
            <p role="status" className="text-xs font-medium text-accent dark:text-accent-dark">
              {formatAutoApplyNotice(planRun.autoApplyAt)}
            </p>
          )}

          {planRun.diff.changes.length > 0 && (
            <div className="flex flex-col gap-2">
              {planRun.diff.changes.map((change: PlanChange) => {
                const pending = pendingEdits[change.id];
                const isRemoved = !!pending?.remove;
                const isEditingThis = editingChangeId === change.id;
                const isEditingTaskDetails = editingTaskId === change.id;
                const effectiveTime =
                  pending?.proposedStartLocal && !isRemoved
                    ? formatDateTime(fromDatetimeLocalValue(pending.proposedStartLocal))
                    : formatDateTime(change.proposedStart);
                const wasEdited = !!pending?.proposedStartLocal && !isRemoved;

                return (
                  <div
                    key={change.id}
                    className={`rounded-control bg-background dark:bg-background-dark px-3 py-2 ${
                      isRemoved ? 'opacity-50' : ''
                    }`}
                  >
                    {isRemoved ? (
                      <div className="flex items-center justify-between gap-2">
                        <p className="text-sm text-text-secondary dark:text-text-secondary-dark line-through">
                          {formatDateTime(change.proposedStart)} — {change.task.title}
                        </p>
                        <button onClick={() => toggleRemove(change.id)} className="shrink-0 text-xs font-medium text-accent">
                          Undo
                        </button>
                      </div>
                    ) : isEditingThis ? (
                      <div className="flex flex-col gap-2">
                        <p className="text-sm text-text-primary dark:text-text-primary-dark">{change.task.title}</p>
                        <input
                          type="datetime-local"
                          value={pending?.proposedStartLocal ?? toDatetimeLocalValue(change.proposedStart)}
                          onChange={(e) =>
                            setPendingEdits((prev) => ({
                              ...prev,
                              [change.id]: { ...prev[change.id], proposedStartLocal: e.target.value },
                            }))
                          }
                          aria-label={`Proposed start time for "${change.task.title}"`}
                          className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                        />
                        <button onClick={() => setEditingChangeId(null)} className="self-start text-xs font-medium text-accent">
                          Done
                        </button>
                      </div>
                    ) : isEditingTaskDetails && taskDraft ? (
                      // See AiPlanCard's identical editor for the full
                      // reasoning — "Save" writes the task immediately.
                      <div className="flex flex-col gap-2">
                        <input
                          type="text"
                          value={taskDraft.title}
                          onChange={(e) => setTaskDraft({ ...taskDraft, title: e.target.value })}
                          aria-label="Task title"
                          className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                        />
                        <div className="flex gap-2">
                          <select
                            value={taskDraft.priority}
                            onChange={(e) => setTaskDraft({ ...taskDraft, priority: parseInt(e.target.value, 10) })}
                            aria-label="Priority"
                            className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                          >
                            <option value={1}>Priority: Urgent</option>
                            <option value={2}>Priority: High</option>
                            <option value={3}>Priority: Normal</option>
                            <option value={4}>Priority: Someday</option>
                          </select>
                          <input
                            type="number"
                            min={1}
                            value={taskDraft.estimatedDurationMinutes}
                            onChange={(e) =>
                              setTaskDraft({ ...taskDraft, estimatedDurationMinutes: parseInt(e.target.value, 10) || 1 })
                            }
                            aria-label="Estimated duration in minutes"
                            className="w-20 rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                          />
                          <span className="self-center text-xs text-text-secondary dark:text-text-secondary-dark">min</span>
                        </div>
                        {taskSaveError && <p className="text-xs text-danger dark:text-danger-dark" role="alert">{taskSaveError}</p>}
                        <div className="flex gap-2">
                          <button
                            disabled={savingTaskDetails}
                            onClick={() => handleSaveTaskDetails(change)}
                            className="text-xs font-medium text-accent disabled:opacity-50"
                          >
                            {savingTaskDetails ? 'Saving…' : 'Save task'}
                          </button>
                          <button
                            onClick={() => {
                              setEditingTaskId(null);
                              setTaskDraft(null);
                              setTaskSaveError(null);
                            }}
                            className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                          >
                            Cancel
                          </button>
                        </div>
                      </div>
                    ) : (
                      <>
                        <p className="text-sm text-text-primary dark:text-text-primary-dark">
                          <span className="font-medium">{effectiveTime}</span> — {change.task.title}
                          {wasEdited && <span className="ml-1 text-xs text-accent">(edited)</span>}
                        </p>
                        <div className="mt-1 flex items-center justify-between gap-2">
                          <p className="text-xs text-text-secondary dark:text-text-secondary-dark">{change.reason}</p>
                          <div className="flex shrink-0 gap-2">
                            <button onClick={() => startEditing(change)} className="text-xs font-medium text-accent">
                              Edit time
                            </button>
                            <button onClick={() => startEditingTask(change)} className="text-xs font-medium text-accent">
                              Edit task
                            </button>
                            <button
                              onClick={() => toggleRemove(change.id)}
                              className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                            >
                              Remove
                            </button>
                          </div>
                        </div>
                      </>
                    )}
                  </div>
                );
              })}
            </div>
          )}

          {/* Free-form plan editing increment: see AiPlanCard's identical
              pending-adds list for the full reasoning. */}
          {Object.values(pendingAdds).length > 0 && (
            <div className="flex flex-col gap-2">
              {Object.values(pendingAdds).map((add) => (
                <div key={add.taskId} className="rounded-control bg-background dark:bg-background-dark px-3 py-2">
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-sm text-text-primary dark:text-text-primary-dark">
                      <span className="font-medium">{formatDateTime(fromDatetimeLocalValue(add.proposedStartLocal))}</span>{' '}
                      — {add.title} <span className="ml-1 text-xs text-accent">(added)</span>
                    </p>
                    <button
                      onClick={() => removePendingAdd(add.taskId)}
                      className="shrink-0 text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Free-form plan editing increment: see AiPlanCard's identical
              add-a-task control for the full reasoning. */}
          {availableTasksToAdd.length > 0 &&
            (isAdding ? (
              <div className="flex flex-col gap-2 rounded-control border border-border dark:border-border-dark px-3 py-2">
                <select
                  value={addTaskId}
                  onChange={(e) => setAddTaskId(e.target.value)}
                  aria-label="Task to add"
                  className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                >
                  <option value="">Pick a task…</option>
                  {availableTasksToAdd.map((t) => (
                    <option key={t.id} value={t.id}>
                      {t.title}
                    </option>
                  ))}
                </select>
                <input
                  type="datetime-local"
                  value={addTimeLocal}
                  onChange={(e) => setAddTimeLocal(e.target.value)}
                  aria-label="Start time for the new task"
                  className="rounded-control border border-border dark:border-border-dark bg-surface dark:bg-surface-dark px-2 py-1 text-xs text-text-primary dark:text-text-primary-dark"
                />
                <div className="flex gap-2">
                  <button
                    onClick={handleAddTask}
                    disabled={!addTaskId || !addTimeLocal}
                    className="text-xs font-medium text-accent disabled:opacity-50"
                  >
                    Add to plan
                  </button>
                  <button
                    onClick={() => {
                      setIsAdding(false);
                      setAddTaskId('');
                      setAddTimeLocal('');
                    }}
                    className="text-xs font-medium text-text-secondary dark:text-text-secondary-dark"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <button onClick={() => setIsAdding(true)} className="self-start text-xs font-medium text-accent">
                + Add a task
              </button>
            ))}

          {hasPendingEdits ? (
            <div className="flex gap-2">
              <button
                disabled={responding}
                onClick={handleSaveEdits}
                className="flex-1 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
              >
                {responding ? 'Saving…' : 'Save & apply changes'}
              </button>
              <button
                disabled={responding}
                onClick={resetLocalEditState}
                className="flex-1 rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-secondary dark:text-text-secondary-dark disabled:opacity-50"
              >
                Discard edits
              </button>
            </div>
          ) : (
            <div className="flex gap-2">
              <button
                disabled={responding}
                onClick={() => handleRespond('ACCEPT')}
                className="flex-1 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
              >
                {responding ? 'Saving…' : `Accept ${scopeLabel} plan`}
              </button>
              <button
                disabled={responding}
                onClick={() => handleRespond('REJECT')}
                className="flex-1 rounded-control border border-border dark:border-border-dark px-3 py-1.5 text-xs font-medium text-text-secondary dark:text-text-secondary-dark disabled:opacity-50"
              >
                Reject
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm text-text-secondary dark:text-text-secondary-dark">
            {querying
              ? 'Loading…'
              : planRun?.status === 'ACCEPTED'
                ? `Your last ${scopeLabel}ly plan was applied. Ask again anytime.`
                : planRun?.status === 'EDITED'
                  ? `Your last ${scopeLabel}ly plan was applied with your edits. Ask again anytime.`
                  : `Let AI spread your open tasks across the ${scopeLabel} ahead.`}
            {(planRun?.status === 'ACCEPTED' || planRun?.status === 'EDITED') &&
              isAutoGenerated(planRun.triggerEvent) && (
                <span className="ml-1.5 rounded-full border border-border dark:border-border-dark px-1.5 py-0.5 text-xs text-text-secondary dark:text-text-secondary-dark">
                  Auto-generated
                </span>
              )}
          </p>
          <button
            disabled={generating}
            onClick={handleGenerate}
            className="shrink-0 rounded-control bg-accent px-3 py-1.5 text-xs font-medium text-white disabled:opacity-50"
          >
            {generating ? 'Thinking…' : `Generate ${scopeLabel} plan`}
          </button>
        </div>
      )}
    </div>
  );
}
