import { test, expect } from '@playwright/test';

test.describe('AI daily plan review', () => {
  test('generating a plan proposes changes, and accepting it applies them', async ({ page }) => {
    // A real call to the AI planner can take longer than Playwright's
    // default 30s per-test timeout on its own — this test already waits up
    // to 90s for the "Accept plan" button specifically (see below), but
    // that inner wait was previously getting cut off by the outer test
    // timeout before it ever got the chance to finish. A first pass at this
    // (60s inner / 90s outer) still wasn't enough in practice — a real run
    // hit the 60s inner timeout while the AI call was still genuinely in
    // flight — so both are raised again here with more headroom.
    test.setTimeout(120_000);

    await page.goto('/today');

    const generateButton = page.getByRole('button', { name: 'Generate my plan' });
    const acceptButton = page.getByRole('button', { name: 'Accept plan' });

    // If this shared dev-auth account already has a PROPOSED plan sitting
    // from an earlier run, "Generate my plan" won't be shown at all — go
    // straight to reviewing what's already there rather than needing a
    // second AI call just to reach the same review UI. `isVisible()` alone
    // doesn't wait for anything — it's an instant, single check — so on a
    // slow initial load it can run before Today's own query has even
    // resolved and wrongly conclude "no button here," skipping the AI call
    // entirely and leaving the test with nothing to review at all (this is
    // what was actually happening: a run failed in ~8s, far too fast to
    // have ever generated or waited on a real plan). `waitFor` gives the
    // page a real window to settle into whichever of the two states it's
    // actually in before deciding.
    const hasGenerateButton = await generateButton
      .waitFor({ state: 'visible', timeout: 15_000 })
      .then(() => true)
      .catch(() => false);

    if (hasGenerateButton) {
      await generateButton.click();
      // A real call to the AI planner, not a canned response — this can
      // take a while, so this spec waits generously rather than assuming a
      // fast, mocked reply.
      await expect(acceptButton).toBeVisible({ timeout: 90_000 });
    } else {
      await expect(acceptButton).toBeVisible({ timeout: 15_000 });
    }

    await expect(page.getByRole('heading', { name: 'Proposed plan' })).toBeVisible({ timeout: 15_000 });
    // Auto-plan indicator increment: a plan generated by tapping the button
    // is 'manual_request', never one of the `auto_*` triggerEvent values —
    // the badge should not appear on a plan reached this way. A real
    // auto-generated badge appearing after a genuine trigger (completing a
    // task, say) is proven at the data layer by the backend e2e suite
    // (`app.e2e-spec.ts`'s "Automatic re-planning" tests assert the exact
    // `triggerEvent` string for all eight real triggers) — not repeated
    // here, since reliably provoking one of those triggers and outrunning
    // its own cooldown from inside a shared-account Playwright spec would
    // be a flakier, weaker signal than the deterministic backend assertion
    // already covering the same fact.
    //
    // Scoped to the daily plan card specifically (`data-testid`, not a
    // page-wide text search): WeeklyPlanCard renders its own, unrelated
    // "Auto-generated" badge right below this one on /today, and this
    // shared dev-auth account genuinely has an applied weekly plan most of
    // the time a full suite run reaches this spec — a page-wide
    // `getByText('Auto-generated')` matches both and fails Playwright's
    // strict mode (>1 element), even though the thing this assertion
    // actually cares about (was *this*, the daily plan, manually
    // requested) is true either way.
    const dailyPlanCard = page.getByTestId('daily-plan-card');
    await expect(dailyPlanCard.getByText('Auto-generated', { exact: true })).not.toBeVisible();
    await acceptButton.click();

    await expect(
      page.getByText(/Your last plan was applied/, { exact: false }),
    ).toBeVisible({ timeout: 15_000 });
    await expect(dailyPlanCard.getByText('Auto-generated', { exact: true })).not.toBeVisible();
  });
});
