import { test, expect } from '@playwright/test';

test.describe('AI daily plan review', () => {
  test('generating a plan proposes changes, and accepting it applies them', async ({ page }) => {
    // A real call to the AI planner can take longer than Playwright's
    // default 30s per-test timeout on its own — this test already waits up
    // to 60s for the "Accept plan" button specifically (see below), but
    // that inner wait was previously getting cut off by the outer test
    // timeout before it ever got the chance to finish.
    test.setTimeout(90_000);

    await page.goto('/today');

    const generateButton = page.getByRole('button', { name: 'Generate my plan' });
    const acceptButton = page.getByRole('button', { name: 'Accept plan' });

    // If this shared dev-auth account already has a PROPOSED plan sitting
    // from an earlier run, "Generate my plan" won't be shown at all — go
    // straight to reviewing what's already there rather than needing a
    // second AI call just to reach the same review UI.
    if (await generateButton.isVisible().catch(() => false)) {
      await generateButton.click();
      // A real call to the AI planner, not a canned response — this can
      // take a while, so this spec waits generously rather than assuming a
      // fast, mocked reply.
      await expect(acceptButton).toBeVisible({ timeout: 60_000 });
    }

    await expect(page.getByRole('heading', { name: 'Proposed plan' })).toBeVisible();
    // Auto-plan indicator increment: a plan generated by tapping the button
    // is 'manual_request', never one of the `auto_*` triggerEvent values —
    // the badge should not appear on a plan reached this way. A real
    // auto-generated badge appearing after a genuine trigger (completing a
    // task, say) is proven at the data layer by the backend e2e suite
    // (`app.e2e-spec.ts`'s "Automatic re-planning" tests assert the exact
    // `triggerEvent` string for all eight real triggers) — not repeated
    // here, since reliably provoking one of those triggers and outrunning
    // its own cooldown from inside a shared-account Playwright spec would
    // be a flakier, weaker signal than the deterministic backend assertion
    // already covering the same fact.
    await expect(page.getByText('Auto-generated', { exact: true })).not.toBeVisible();
    await acceptButton.click();

    await expect(
      page.getByText(/Your last plan was applied/, { exact: false }),
    ).toBeVisible({ timeout: 15_000 });
    await expect(page.getByText('Auto-generated', { exact: true })).not.toBeVisible();
  });
});
