import { Field, ID, ObjectType, registerEnumType } from '@nestjs/graphql';
import { Task } from '../../tasks/models/task.model';

// Only MOVE is ever produced by this increment's PlannerService — CREATE
// (e.g. AI-suggested focus/break blocks) / DELETE / RESIZE are reserved for
// when the AI layer can propose calendar changes too, not just task
// placement (same "reserve the enum value, defer the behavior" pattern
// used throughout this codebase).
export enum PlanChangeType {
  MOVE = 'MOVE',
  CREATE = 'CREATE',
  DELETE = 'DELETE',
  RESIZE = 'RESIZE',
}
registerEnumType(PlanChangeType, { name: 'PlanChangeType' });

// Mirrors PlanChange in the API Design Document §4.4. `task` is resolved
// from the stored taskId at read time (planner.service.ts's hydrateDiff) —
// nullable because the referenced task could have been deleted since the
// plan was generated, which is treated as "this change no longer applies"
// rather than an error.
@ObjectType()
export class PlanChange {
  // Editing a proposed AI plan increment: a stable per-change id (a real
  // UUID, generated once at plan-generation time — see
  // PlannerService.requestReplan) that PlanChangeEditInput.changeId
  // references to target a specific suggestion for a time-tweak or removal.
  // Every change on a plan generated by this increment or later has one;
  // a plan generated before it never had this field stored at all, so
  // PlannerService.hydrate backfills a non-null-but-unstable placeholder
  // for those — editing simply can't target a change from a plan that
  // predates this increment (see README).
  @Field(() => ID)
  id!: string;

  @Field(() => PlanChangeType)
  changeType!: PlanChangeType;

  @Field(() => Task, { nullable: true })
  task?: Task;

  @Field({ nullable: true })
  previousStart?: Date;

  @Field({ nullable: true })
  proposedStart?: Date;

  @Field({ nullable: true })
  proposedEnd?: Date;

  @Field()
  reason!: string;
}

@ObjectType()
export class PlanDiff {
  @Field()
  summary!: string;

  @Field(() => [PlanChange])
  changes!: PlanChange[];
}
